// ---------------------------------------------------------------------------
// continuation.markers.ts
// Continuation and follow-up markers
// ---------------------------------------------------------------------------

import type { SemanticMarker } from "../types/marker.types";

export const CONTINUATION_MARKERS: SemanticMarker[] = [
  {
    id: "cont_and_how_would_you",
    phrase: "and how would you",
    type: "phrase",
    weight: 0.85,
    category: "continuation",
  },
  {
    id: "cont_what_about",
    phrase: "what about",
    type: "phrase",
    weight: 0.82,
    category: "continuation",
  },
  {
    id: "cont_also",
    phrase: "also",
    type: "phrase",
    weight: 0.75,
    category: "continuation",
  },
  {
    id: "cont_then_how",
    phrase: "then how",
    type: "phrase",
    weight: 0.82,
    category: "continuation",
  },
  {
    id: "cont_can_you_elaborate",
    phrase: "can you elaborate",
    type: "phrase",
    weight: 0.88,
    category: "continuation",
  },
  {
    id: "cont_what_if",
    phrase: "what if",
    type: "phrase",
    weight: 0.82,
    category: "continuation",
  },
  {
    id: "cont_and_then",
    phrase: "and then",
    type: "phrase",
    weight: 0.78,
    category: "continuation",
  },
  {
    id: "cont_how_about",
    phrase: "how about",
    type: "phrase",
    weight: 0.82,
    category: "continuation",
  },
  {
    id: "cont_could_you_explain_more",
    phrase: "could you explain more",
    type: "phrase",
    weight: 0.88,
    category: "continuation",
  },
  {
    id: "cont_go_on",
    phrase: "go on",
    type: "phrase",
    weight: 0.80,
    category: "continuation",
  },
  {
    id: "cont_continue",
    phrase: "continue",
    type: "phrase",
    weight: 0.80,
    category: "continuation",
  },
  {
    id: "cont_and_why",
    phrase: "and why",
    type: "phrase",
    weight: 0.78,
    category: "continuation",
  },
  {
    id: "cont_but_what_if",
    phrase: "but what if",
    type: "phrase",
    weight: 0.82,
    category: "continuation",
  },
  {
    id: "cont_follow_up",
    phrase: "follow up",
    type: "phrase",
    weight: 0.85,
    category: "continuation",
  },
  {
    id: "cont_still_on_that",
    phrase: "still on that",
    type: "phrase",
    weight: 0.82,
    category: "continuation",
  },
  {
    id: "cont_building_on_that",
    phrase: "building on that",
    type: "phrase",
    weight: 0.88,
    category: "continuation",
  },
  {
    id: "cont_going_back_to",
    phrase: "going back to",
    type: "phrase",
    weight: 0.82,
    category: "continuation",
  },
  {
    id: "cont_digging_deeper",
    phrase: "digging deeper",
    type: "phrase",
    weight: 0.85,
    category: "continuation",
  },
  {
    id: "cont_on_that_note",
    phrase: "on that note",
    type: "phrase",
    weight: 0.82,
    category: "continuation",
  },
  {
    id: "cont_what_would",
    phrase: "and what would",
    type: "phrase",
    weight: 0.82,
    category: "continuation",
  },
  {
    id: "cont_moving_on_from",
    phrase: "moving on from that",
    type: "phrase",
    weight: 0.82,
    category: "continuation",
  },
  {
    id: "cont_following_up_on",
    phrase: "following up on",
    type: "phrase",
    weight: 0.88,
    category: "continuation",
  },
  {
    id: "cont_expand_on",
    phrase: "to expand on that",
    type: "phrase",
    weight: 0.88,
    category: "continuation",
  },
  {
    id: "cont_more_specifically",
    phrase: "more specifically",
    type: "phrase",
    weight: 0.82,
    category: "continuation",
  },
];
