// ---------------------------------------------------------------------------
// filler.markers.ts
// Filler and noise markers (negative scoring)
// ---------------------------------------------------------------------------

import type { SemanticMarker } from "../types/marker.types";

export const FILLER_MARKERS: SemanticMarker[] = [
  {
    id: "filler_um",
    phrase: "um",
    type: "phrase",
    weight: 0.70,
    category: "filler",
    negative: true,
  },
  {
    id: "filler_uh",
    phrase: "uh",
    type: "phrase",
    weight: 0.70,
    category: "filler",
    negative: true,
  },
  {
    id: "filler_okay",
    phrase: "okay",
    type: "phrase",
    weight: 0.70,
    category: "filler",
    negative: true,
  },
  {
    id: "filler_sure",
    phrase: "sure",
    type: "phrase",
    weight: 0.70,
    category: "filler",
    negative: true,
  },
  {
    id: "filler_yeah",
    phrase: "yeah",
    type: "phrase",
    weight: 0.70,
    category: "filler",
    negative: true,
  },
  {
    id: "filler_hmm",
    phrase: "hmm",
    type: "phrase",
    weight: 0.70,
    category: "filler",
    negative: true,
  },
  {
    id: "filler_mm",
    phrase: "mm",
    type: "phrase",
    weight: 0.70,
    category: "filler",
    negative: true,
  },
  {
    id: "filler_ah",
    phrase: "ah",
    type: "phrase",
    weight: 0.70,
    category: "filler",
    negative: true,
  },
  {
    id: "filler_oh",
    phrase: "oh",
    type: "phrase",
    weight: 0.70,
    category: "filler",
    negative: true,
  },
  {
    id: "filler_right",
    phrase: "right",
    type: "phrase",
    weight: 0.70,
    category: "filler",
    negative: true,
  },
  {
    id: "filler_like",
    phrase: "like",
    type: "phrase",
    weight: 0.65,
    category: "filler",
    negative: true,
  },
  {
    id: "filler_you_know",
    phrase: "you know",
    type: "phrase",
    weight: 0.70,
    category: "filler",
    negative: true,
  },
  {
    id: "filler_so",
    phrase: "so",
    type: "phrase",
    weight: 0.60,
    category: "filler",
    negative: true,
  },
  {
    id: "filler_well",
    phrase: "well",
    type: "phrase",
    weight: 0.65,
    category: "filler",
    negative: true,
  },
  {
    id: "filler_huh",
    phrase: "huh",
    type: "phrase",
    weight: 0.70,
    category: "filler",
    negative: true,
  },
  {
    id: "filler_mhm",
    phrase: "mhm",
    type: "phrase",
    weight: 0.70,
    category: "filler",
    negative: true,
  },
];
