// ---------------------------------------------------------------------------
// scenario.markers.ts
// Scenario-based question markers for interview contexts
// ---------------------------------------------------------------------------

import type { SemanticMarker } from "../types/marker.types";

export const SCENARIO_MARKERS: SemanticMarker[] = [
  // Classic scenario starters
  {
    id: "scenario_suppose",
    phrase: "suppose",
    type: "phrase",
    weight: 0.85,
    category: "scenario_based",
  },
  {
    id: "scenario_imagine",
    phrase: "imagine",
    type: "phrase",
    weight: 0.85,
    category: "scenario_based",
  },
  {
    id: "scenario_design_a",
    phrase: "design a",
    type: "phrase",
    weight: 0.90,
    category: "scenario_based",
  },
  {
    id: "scenario_build_a",
    phrase: "build a",
    type: "phrase",
    weight: 0.90,
    category: "scenario_based",
  },
  {
    id: "scenario_what_would_you_do_if",
    phrase: "what would you do if",
    type: "phrase",
    weight: 0.92,
    category: "scenario_based",
  },
  {
    id: "scenario_lets_say",
    phrase: "let's say",
    type: "phrase",
    weight: 0.88,
    category: "scenario_based",
  },
  {
    id: "scenario_consider_scenario",
    phrase: "consider a scenario",
    type: "phrase",
    weight: 0.90,
    category: "scenario_based",
  },
  {
    id: "scenario_how_would_you_approach",
    phrase: "how would you approach",
    type: "phrase",
    weight: 0.88,
    category: "scenario_based",
  },
  {
    id: "scenario_walk_me_through",
    phrase: "walk me through",
    type: "phrase",
    weight: 0.85,
    category: "scenario_based",
  },
  {
    id: "scenario_if_you_were_to_build",
    phrase: "if you were to build",
    type: "phrase",
    weight: 0.90,
    category: "scenario_based",
  },
  {
    id: "scenario_if_you_had_to_design",
    phrase: "if you had to design",
    type: "phrase",
    weight: 0.90,
    category: "scenario_based",
  },
  {
    id: "scenario_picture_this",
    phrase: "picture this",
    type: "phrase",
    weight: 0.85,
    category: "scenario_based",
  },
  {
    id: "scenario_envision_a",
    phrase: "envision a",
    type: "phrase",
    weight: 0.85,
    category: "scenario_based",
  },
  {
    id: "scenario_say_you_have",
    phrase: "say you have",
    type: "phrase",
    weight: 0.85,
    category: "scenario_based",
  },
  {
    id: "scenario_say_you_are",
    phrase: "say you are",
    type: "phrase",
    weight: 0.85,
    category: "scenario_based",
  },
  {
    id: "scenario_pretend_you",
    phrase: "pretend you",
    type: "phrase",
    weight: 0.85,
    category: "scenario_based",
  },
  {
    id: "scenario_lets_assume",
    phrase: "let's assume",
    type: "phrase",
    weight: 0.88,
    category: "scenario_based",
  },
  {
    id: "scenario_given_scenario",
    phrase: "given a scenario",
    type: "phrase",
    weight: 0.90,
    category: "scenario_based",
  },
  {
    id: "scenario_in_situation_where",
    phrase: "in a situation where",
    type: "phrase",
    weight: 0.88,
    category: "scenario_based",
  },
  {
    id: "scenario_tasked_with",
    phrase: "you are tasked with",
    type: "phrase",
    weight: 0.90,
    category: "scenario_based",
  },
  
  // Narrative setup markers (high confidence for scenario detection)
  {
    id: "scenario_your_team_has",
    phrase: "your team has",
    type: "phrase",
    weight: 0.95,
    category: "scenario_based",
  },
  {
    id: "scenario_your_team",
    phrase: "your team",
    type: "phrase",
    weight: 0.88,
    category: "scenario_based",
  },
  {
    id: "scenario_a_user_clicks",
    phrase: "a user clicks",
    type: "phrase",
    weight: 0.92,
    category: "scenario_based",
  },
  {
    id: "scenario_a_user",
    phrase: "a user",
    type: "phrase",
    weight: 0.80,
    category: "scenario_based",
  },
  {
    id: "scenario_another_user",
    phrase: "another user",
    type: "phrase",
    weight: 0.90,
    category: "scenario_based",
  },
  {
    id: "scenario_at_same_time",
    phrase: "at the same time",
    type: "phrase",
    weight: 0.92,
    category: "scenario_based",
  },
  {
    id: "scenario_simultaneously",
    phrase: "simultaneously",
    type: "phrase",
    weight: 0.90,
    category: "scenario_based",
  },
  {
    id: "scenario_concurrently",
    phrase: "concurrently",
    type: "phrase",
    weight: 0.90,
    category: "scenario_based",
  },
  {
    id: "scenario_writes_overwrite",
    phrase: "writes overwrite",
    type: "phrase",
    weight: 0.92,
    category: "scenario_based",
  },
  {
    id: "scenario_data_integrity",
    phrase: "data integrity",
    type: "phrase",
    weight: 0.88,
    category: "scenario_based",
  },
  {
    id: "scenario_high_traffic",
    phrase: "high traffic",
    type: "phrase",
    weight: 0.88,
    category: "scenario_based",
  },
  {
    id: "scenario_collaborative",
    phrase: "collaborative",
    type: "phrase",
    weight: 0.82,
    category: "scenario_based",
  },
  {
    id: "scenario_dashboard",
    phrase: "dashboard",
    type: "phrase",
    weight: 0.75,
    category: "scenario_based",
  },
  {
    id: "scenario_deployed",
    phrase: "deployed",
    type: "phrase",
    weight: 0.80,
    category: "scenario_based",
  },
  {
    id: "scenario_race_condition",
    phrase: "race condition",
    type: "phrase",
    weight: 0.95,
    category: "scenario_based",
  },
  {
    id: "scenario_concurrency_conflict",
    phrase: "concurrency conflict",
    type: "phrase",
    weight: 0.95,
    category: "scenario_based",
  },
  {
    id: "scenario_without_locking",
    phrase: "without locking",
    type: "phrase",
    weight: 0.90,
    category: "scenario_based",
  },
  
  // Regex patterns for complex scenario structures
  {
    id: "scenario_your_team_regex",
    regex: /your team (has|is|was)/i,
    type: "regex",
    weight: 0.95,
    category: "scenario_based",
  },
  {
    id: "scenario_a_user_clicks_regex",
    regex: /a user (clicks|click|does|did)/i,
    type: "regex",
    weight: 0.92,
    category: "scenario_based",
  },
  {
    id: "scenario_another_user_regex",
    regex: /another user/i,
    type: "regex",
    weight: 0.90,
    category: "scenario_based",
  },
  {
    id: "scenario_race_condition_regex",
    regex: /race condition/i,
    type: "regex",
    weight: 0.95,
    category: "scenario_based",
  },
  {
    id: "scenario_concurrency_regex",
    regex: /concurrency (conflict|issue|problem)/i,
    type: "regex",
    weight: 0.95,
    category: "scenario_based",
  },
];
