// ---------------------------------------------------------------------------
// system-design.markers.ts
// System design and architecture markers
// ---------------------------------------------------------------------------

import type { SemanticMarker } from "../types/marker.types";

export const SYSTEM_DESIGN_MARKERS: SemanticMarker[] = [
  {
    id: "sd_scale",
    phrase: "scale",
    type: "phrase",
    weight: 0.88,
    category: "system_design",
  },
  {
    id: "sd_architecture",
    phrase: "architecture",
    type: "phrase",
    weight: 0.90,
    category: "system_design",
  },
  {
    id: "sd_database",
    phrase: "database",
    type: "phrase",
    weight: 0.82,
    category: "system_design",
  },
  {
    id: "sd_cache",
    phrase: "cache",
    type: "phrase",
    weight: 0.85,
    category: "system_design",
  },
  {
    id: "sd_load_balancer",
    phrase: "load balancer",
    type: "phrase",
    weight: 0.92,
    category: "system_design",
  },
  {
    id: "sd_microservices",
    phrase: "microservices",
    type: "phrase",
    weight: 0.92,
    category: "system_design",
  },
  {
    id: "sd_distributed",
    phrase: "distributed",
    type: "phrase",
    weight: 0.88,
    category: "system_design",
  },
  {
    id: "sd_high_availability",
    phrase: "high availability",
    type: "phrase",
    weight: 0.92,
    category: "system_design",
  },
  {
    id: "sd_latency",
    phrase: "latency",
    type: "phrase",
    weight: 0.85,
    category: "system_design",
  },
  {
    id: "sd_throughput",
    phrase: "throughput",
    type: "phrase",
    weight: 0.88,
    category: "system_design",
  },
  {
    id: "sd_sharding",
    phrase: "sharding",
    type: "phrase",
    weight: 0.92,
    category: "system_design",
  },
  {
    id: "sd_replication",
    phrase: "replication",
    type: "phrase",
    weight: 0.90,
    category: "system_design",
  },
  {
    id: "sd_cdn",
    phrase: "cdn",
    type: "phrase",
    weight: 0.85,
    category: "system_design",
  },
  {
    id: "sd_message_queue",
    phrase: "message queue",
    type: "phrase",
    weight: 0.92,
    category: "system_design",
  },
  {
    id: "sd_consistency",
    phrase: "consistency",
    type: "phrase",
    weight: 0.88,
    category: "system_design",
  },
  {
    id: "sd_partitioning",
    phrase: "partitioning",
    type: "phrase",
    weight: 0.90,
    category: "system_design",
  },
  {
    id: "sd_fault_tolerance",
    phrase: "fault tolerance",
    type: "phrase",
    weight: 0.92,
    category: "system_design",
  },
  {
    id: "sd_horizontal_scaling",
    phrase: "horizontal scaling",
    type: "phrase",
    weight: 0.92,
    category: "system_design",
  },
  {
    id: "sd_vertical_scaling",
    phrase: "vertical scaling",
    type: "phrase",
    weight: 0.90,
    category: "system_design",
  },
  {
    id: "sd_rate_limiting",
    phrase: "rate limiting",
    type: "phrase",
    weight: 0.90,
    category: "system_design",
  },
  {
    id: "sd_circuit_breaker",
    phrase: "circuit breaker",
    type: "phrase",
    weight: 0.92,
    category: "system_design",
  },
  {
    id: "sd_service_mesh",
    phrase: "service mesh",
    type: "phrase",
    weight: 0.92,
    category: "system_design",
  },
  {
    id: "sd_api_gateway",
    phrase: "api gateway",
    type: "phrase",
    weight: 0.90,
    category: "system_design",
  },
  {
    id: "sd_event_driven",
    phrase: "event driven",
    type: "phrase",
    weight: 0.88,
    category: "system_design",
  },
  {
    id: "sd_event_sourcing",
    phrase: "event sourcing",
    type: "phrase",
    weight: 0.92,
    category: "system_design",
  },
  {
    id: "sd_cap_theorem",
    phrase: "cap theorem",
    type: "phrase",
    weight: 0.92,
    category: "system_design",
  },
  {
    id: "sd_eventual_consistency",
    phrase: "eventual consistency",
    type: "phrase",
    weight: 0.90,
    category: "system_design",
  },
  {
    id: "sd_concurrency",
    phrase: "concurrency",
    type: "phrase",
    weight: 0.88,
    category: "system_design",
  },
  {
    id: "sd_bottleneck",
    phrase: "bottleneck",
    type: "phrase",
    weight: 0.85,
    category: "system_design",
  },
  {
    id: "sd_capacity",
    phrase: "capacity",
    type: "phrase",
    weight: 0.82,
    category: "system_design",
  },
  {
    id: "sd_deploy",
    phrase: "deploy",
    type: "phrase",
    weight: 0.80,
    category: "system_design",
  },
  {
    id: "sd_infrastructure",
    phrase: "infrastructure",
    type: "phrase",
    weight: 0.85,
    category: "system_design",
  },
  {
    id: "sd_redundancy",
    phrase: "redundancy",
    type: "phrase",
    weight: 0.85,
    category: "system_design",
  },
  
  // High-weight system design phrases
  {
    id: "sd_how_would_you_scale",
    phrase: "how would you scale",
    type: "phrase",
    weight: 0.95,
    category: "system_design",
  },
  {
    id: "sd_design_scalable",
    phrase: "design a scalable",
    type: "phrase",
    weight: 0.95,
    category: "system_design",
  },
  {
    id: "sd_millions_of_users",
    phrase: "millions of users",
    type: "phrase",
    weight: 0.92,
    category: "system_design",
  },
  {
    id: "sd_high_traffic",
    phrase: "high traffic",
    type: "phrase",
    weight: 0.90,
    category: "system_design",
  },
];
