export const STT_CORRECTIONS: Array<[RegExp, string]> = [
  // =========================
  // Core tech / interview words
  // =========================
  [/\btext stack\b/gi, "tech stack"],
  [/\btext stacks\b/gi, "tech stacks"],
  [/\btext sex stack\b/gi, "tech stack"],
  [/\btech sex stack\b/gi, "tech stack"],
  [/\btechnical stack\b/gi, "tech stack"],
  [/\btechnology stack\b/gi, "tech stack"],
  [/\bfront and\b/gi, "frontend"],
  [/\bfront end\b/gi, "frontend"],
  [/\bfront-end\b/gi, "frontend"],
  [/\bback and\b/gi, "backend"],
  [/\bback end\b/gi, "backend"],
  [/\bback-end\b/gi, "backend"],
  [/\bfull stack\b/gi, "full-stack"],
  [/\bfull stuck\b/gi, "full-stack"],
  [/\bmern\b/gi, "MERN"],
  [/\bm e r n\b/gi, "MERN"],
  [/\bmean stack\b/gi, "MEAN stack"],
  [/\bm e a n\b/gi, "MEAN"],
  [/\bsoftware develop ment\b/gi, "software development"],
  [/\bweb develop ment\b/gi, "web development"],
  [/\bprogram ming\b/gi, "programming"],
  [/\bdebug ging\b/gi, "debugging"],
  [/\btrouble shooting\b/gi, "troubleshooting"],

  // =========================
  // JavaScript / TypeScript
  // =========================
  [/\bjava script\b/gi, "JavaScript"],
  [/\bjawa script\b/gi, "JavaScript"],
  [/\bjava scripts\b/gi, "JavaScript"],
  [/\bjs\b/g, "JS"],
  [/\bj s\b/gi, "JS"],
  [/\btype script\b/gi, "TypeScript"],
  [/\btypes script\b/gi, "TypeScript"],
  [/\bt s\b/gi, "TS"],
  [/\becma script\b/gi, "ECMAScript"],
  [/\bes six\b/gi, "ES6"],
  [/\bes 6\b/gi, "ES6"],
  [/\bvanilla js\b/gi, "vanilla JS"],
  [/\basync await\b/gi, "async/await"],
  [/\ba sync await\b/gi, "async/await"],
  [/\bpromises\b/gi, "Promises"],
  [/\bcallback function\b/gi, "callback function"],
  [/\bcall back\b/gi, "callback"],
  [/\bevent loop\b/gi, "event loop"],
  [/\bclosure\b/gi, "closure"],
  [/\bhoisting\b/gi, "hoisting"],
  [/\bdebounce\b/gi, "debounce"],
  [/\bde bounce\b/gi, "debounce"],
  [/\bthrottle\b/gi, "throttle"],
  [/\bmap filter reduce\b/gi, "map, filter, reduce"],
  [/\bspread operator\b/gi, "spread operator"],
  [/\brest operator\b/gi, "rest operator"],
  [/\bdestructuring\b/gi, "destructuring"],
  [/\bde structuring\b/gi, "destructuring"],

  // =========================
  // React / frontend
  // =========================
  [/\breact js\b/gi, "React"],
  [/\breact j s\b/gi, "React"],
  [/\breacts\b/gi, "React"],
  [/\bnext js\b/gi, "Next.js"],
  [/\bnext j s\b/gi, "Next.js"],
  [/\bnuxt js\b/gi, "Nuxt.js"],
  [/\bview js\b/gi, "Vue.js"],
  [/\bvue js\b/gi, "Vue.js"],
  [/\bangular js\b/gi, "AngularJS"],
  [/\bangular\b/gi, "Angular"],
  [/\buser[\s.]+effect\b/gi, "useEffect"],
  [/\buse\s+effect\b/gi, "useEffect"],
  [/\buse affects\b/gi, "useEffect"],
  [/\buse state\b/gi, "useState"],
  [/\buser state\b/gi, "useState"],
  [/\buse memo\b/gi, "useMemo"],
  [/\buse callback\b/gi, "useCallback"],
  [/\buse context\b/gi, "useContext"],
  [/\buse ref\b/gi, "useRef"],
  [/\breact hook\b/gi, "React hook"],
  [/\breact hooks\b/gi, "React hooks"],
  [/\bcustom hook\b/gi, "custom hook"],
  [/\bcustom hooks\b/gi, "custom hooks"],
  [/\bcomponent life cycle\b/gi, "component lifecycle"],
  [/\blife cycle method\b/gi, "lifecycle method"],
  [/\bvirtual dom\b/gi, "Virtual DOM"],
  [/\breal dom\b/gi, "real DOM"],
  [/\bprops drilling\b/gi, "prop drilling"],
  [/\bprop drilling\b/gi, "prop drilling"],
  [/\bstate management\b/gi, "state management"],
  [/\bredux tool kit\b/gi, "Redux Toolkit"],
  [/\bredux toolkit\b/gi, "Redux Toolkit"],
  [/\bredux store\b/gi, "Redux store"],
  [/\bredux slice\b/gi, "Redux slice"],
  [/\bcontext api\b/gi, "Context API"],
  [/\bmaterial ui\b/gi, "Material UI"],
  [/\bmui\b/gi, "MUI"],
  [/\btail wind\b/gi, "Tailwind"],
  [/\btailwind css\b/gi, "Tailwind CSS"],
  [/\bshad cn\b/gi, "shadcn"],
  [/\bshadcn ui\b/gi, "shadcn/ui"],
  [/\bchakra ui\b/gi, "Chakra UI"],
  [/\bbootstrap\b/gi, "Bootstrap"],
  [/\bresponsive design\b/gi, "responsive design"],
  [/\bmedia query\b/gi, "media query"],
  [/\bmedia queries\b/gi, "media queries"],
  [/\bcss\b/g, "CSS"],
  [/\bc s s\b/gi, "CSS"],
  [/\bhtml\b/g, "HTML"],
  [/\bh t m l\b/gi, "HTML"],
  [/\bsass\b/gi, "Sass"],
  [/\bscss\b/gi, "SCSS"],
  [/\bweb pack\b/gi, "Webpack"],
  [/\bwebpack\b/gi, "Webpack"],
  [/\bvite\b/gi, "Vite"],
  [/\bveet\b/gi, "Vite"],

  // =========================
  // Node / backend
  // =========================
  [/\bnode js\b/gi, "Node.js"],
  [/\bnode j s\b/gi, "Node.js"],
  [/\bnode dot js\b/gi, "Node.js"],
  [/\bexpress js\b/gi, "Express.js"],
  [/\bexpress j s\b/gi, "Express.js"],
  [/\bexpress server\b/gi, "Express server"],
  [/\bnest js\b/gi, "NestJS"],
  [/\bnest j s\b/gi, "NestJS"],
  [/\bfastify\b/gi, "Fastify"],
  [/\brest full\b/gi, "RESTful"],
  [/\brestful api\b/gi, "RESTful API"],
  [/\brest api\b/gi, "REST API"],
  [/\brest apis\b/gi, "REST APIs"],
  [/\bapi\b/g, "API"],
  [/\ba p i\b/gi, "API"],
  [/\bai pi\b/gi, "API"],
  [/\bapis\b/gi, "APIs"],
  [/\ba p is\b/gi, "APIs"],
  [/\bcrud\b/gi, "CRUD"],
  [/\bc r u d\b/gi, "CRUD"],
  [/\bcreate read update delete\b/gi, "create, read, update, delete"],
  [/\bmiddleware\b/gi, "middleware"],
  [/\bmiddle ware\b/gi, "middleware"],
  [/\bcontroller service pattern\b/gi, "controller-service pattern"],
  [/\broute handler\b/gi, "route handler"],
  [/\brequest response\b/gi, "request-response"],
  [/\bserver side\b/gi, "server-side"],
  [/\bserver sent events\b/gi, "Server-Sent Events"],
  [/\bsse\b/g, "SSE"],
  [/\bs s e\b/gi, "SSE"],
  [/\bweb socket\b/gi, "WebSocket"],
  [/\bweb sockets\b/gi, "WebSockets"],
  [/\bwebsocket\b/gi, "WebSocket"],
  [/\bsocket io\b/gi, "Socket.IO"],
  [/\bgraphql\b/gi, "GraphQL"],
  [/\bgraph ql\b/gi, "GraphQL"],
  [/\bgrpc\b/gi, "gRPC"],
  [/\bg r p c\b/gi, "gRPC"],
  [/\brpc\b/gi, "RPC"],

  // =========================
  // Databases / ORM
  // =========================
  [/\bmy sequel\b/gi, "MySQL"],
  [/\bmysql\b/gi, "MySQL"],
  [/\bm y s q l\b/gi, "MySQL"],
  [/\bpost gres\b/gi, "Postgres"],
  [/\bpost gress\b/gi, "Postgres"],
  [/\bpost grey s\b/gi, "Postgres"],
  [/\bpostgres\b/gi, "Postgres"],
  [/\bpostgresql\b/gi, "PostgreSQL"],
  [/\bpostgre sql\b/gi, "PostgreSQL"],
  [/\bpost gres q l\b/gi, "PostgreSQL"],
  [/\bmongo db\b/gi, "MongoDB"],
  [/\bmongo d b\b/gi, "MongoDB"],
  [/\bmongodb\b/gi, "MongoDB"],
  [/\bmongoose\b/gi, "Mongoose"],
  [/\bno sequel\b/gi, "NoSQL"],
  [/\bno sql\b/gi, "NoSQL"],
  [/\bsql\b/g, "SQL"],
  [/\bs q l\b/gi, "SQL"],
  [/\bsequel query\b/gi, "SQL query"],
  [/\braw sql\b/gi, "raw SQL"],
  [/\bprisma\b/gi, "Prisma"],
  [/\bprisma orm\b/gi, "Prisma ORM"],
  [/\btype orm\b/gi, "TypeORM"],
  [/\bsequelize\b/gi, "Sequelize"],
  [/\bredis\b/gi, "Redis"],
  [/\bred is\b/gi, "Redis"],
  [/\belastic search\b/gi, "Elasticsearch"],
  [/\bopensearch\b/gi, "OpenSearch"],
  [/\bopen search\b/gi, "OpenSearch"],
  [/\bpg vector\b/gi, "pgvector"],
  [/\bpgvector\b/gi, "pgvector"],
  [/\bvector db\b/gi, "vector DB"],
  [/\bvector database\b/gi, "vector database"],
  [/\bembedding\b/gi, "embedding"],
  [/\bembeddings\b/gi, "embeddings"],
  [/\bindexing\b/gi, "indexing"],
  [/\bindex\b/gi, "index"],
  [/\bforeign key\b/gi, "foreign key"],
  [/\bprimary key\b/gi, "primary key"],
  [/\bcomposite index\b/gi, "composite index"],
  [/\bjoin query\b/gi, "join query"],
  [/\bleft join\b/gi, "LEFT JOIN"],
  [/\bright join\b/gi, "RIGHT JOIN"],
  [/\binner join\b/gi, "INNER JOIN"],
  [/\btransaction\b/gi, "transaction"],
  [/\btransactions\b/gi, "transactions"],
  [/\bnormalization\b/gi, "normalization"],
  [/\bdenormalization\b/gi, "denormalization"],
  [/\bdata modeling\b/gi, "data modeling"],

  // =========================
  // Auth / security
  // =========================
  [/\bj w t\b/gi, "JWT"],
  [/\bjwt\b/gi, "JWT"],
  [/\bjson web token\b/gi, "JSON Web Token"],
  [/\bo auth\b/gi, "OAuth"],
  [/\boauth\b/gi, "OAuth"],
  [/\bo auth two\b/gi, "OAuth 2.0"],
  [/\boauth 2\b/gi, "OAuth 2.0"],
  [/\bsso\b/gi, "SSO"],
  [/\bs s o\b/gi, "SSO"],
  [/\brbac\b/gi, "RBAC"],
  [/\br b a c\b/gi, "RBAC"],
  [/\bauthentication\b/gi, "authentication"],
  [/\bauthorization\b/gi, "authorization"],
  [/\bauth token\b/gi, "auth token"],
  [/\baccess token\b/gi, "access token"],
  [/\brefresh token\b/gi, "refresh token"],
  [/\bsession cookie\b/gi, "session cookie"],
  [/\bhttp only\b/gi, "HttpOnly"],
  [/\bcsrf\b/gi, "CSRF"],
  [/\bc s r f\b/gi, "CSRF"],
  [/\bxss\b/gi, "XSS"],
  [/\bx s s\b/gi, "XSS"],
  [/\bsql injection\b/gi, "SQL injection"],
  [/\brate limiting\b/gi, "rate limiting"],
  [/\bcrypt\b/gi, "bcrypt"],
  [/\bhashing\b/gi, "hashing"],
  [/\bencryption\b/gi, "encryption"],

  // =========================
  // Cloud / DevOps / CI-CD
  // =========================
  [/\bgit hub\b/gi, "GitHub"],
  [/\bgithub\b/gi, "GitHub"],
  [/\bgit lab\b/gi, "GitLab"],
  [/\bgitlab\b/gi, "GitLab"],
  [/\bbit bucket\b/gi, "Bitbucket"],
  [/\bbitbucket\b/gi, "Bitbucket"],
  [/\bgit action\b/gi, "GitHub Action"],
  [/\bgit actions\b/gi, "GitHub Actions"],
  [/\bgithub action\b/gi, "GitHub Action"],
  [/\bgithub actions\b/gi, "GitHub Actions"],
  [/\bci cd\b/gi, "CI/CD"],
  [/\bc i c d\b/gi, "CI/CD"],
  [/\bcontinuous integration\b/gi, "continuous integration"],
  [/\bcontinuous deployment\b/gi, "continuous deployment"],
  [/\bdocker file\b/gi, "Dockerfile"],
  [/\bdockerfile\b/gi, "Dockerfile"],
  [/\bdocker compose\b/gi, "Docker Compose"],
  [/\bdocker-compose\b/gi, "Docker Compose"],
  [/\bdocker image\b/gi, "Docker image"],
  [/\bdocker container\b/gi, "Docker container"],
  [/\bcontainerization\b/gi, "containerization"],
  [/\bkube rnetes\b/gi, "Kubernetes"],
  [/\bcube rnetes\b/gi, "Kubernetes"],
  [/\bkubernetes\b/gi, "Kubernetes"],
  [/\bk eight s\b/gi, "K8s"],
  [/\bk8s\b/gi, "K8s"],
  [/\bhelm chart\b/gi, "Helm chart"],
  [/\baws\b/g, "AWS"],
  [/\ba w s\b/gi, "AWS"],
  [/\bec two\b/gi, "EC2"],
  [/\be c two\b/gi, "EC2"],
  [/\bs three\b/gi, "S3"],
  [/\bs 3\b/gi, "S3"],
  [/\brds\b/gi, "RDS"],
  [/\br d s\b/gi, "RDS"],
  [/\blambda function\b/gi, "Lambda function"],
  [/\bcloud front\b/gi, "CloudFront"],
  [/\bcloud watch\b/gi, "CloudWatch"],
  [/\bazure\b/gi, "Azure"],
  [/\bgcp\b/gi, "GCP"],
  [/\bg c p\b/gi, "GCP"],
  [/\bgoogle cloud\b/gi, "Google Cloud"],
  [/\bvercel\b/gi, "Vercel"],
  [/\bnetlify\b/gi, "Netlify"],
  [/\brender dot com\b/gi, "Render"],
  [/\bdigital ocean\b/gi, "DigitalOcean"],
  [/\bnginx\b/gi, "Nginx"],
  [/\bn gin x\b/gi, "Nginx"],
  [/\bload balancer\b/gi, "load balancer"],
  [/\breverse proxy\b/gi, "reverse proxy"],
  [/\bssl\b/gi, "SSL"],
  [/\btls\b/gi, "TLS"],
  [/\bhttps\b/gi, "HTTPS"],
  [/\bhttp\b/gi, "HTTP"],

  // =========================
  // Architecture
  // =========================
  [/\bmicro service\b/gi, "microservice"],
  [/\bmicro services\b/gi, "microservices"],
  [/\bmicroservice architecture\b/gi, "microservice architecture"],
  [/\bmonolith\b/gi, "monolith"],
  [/\bmonolithic\b/gi, "monolithic"],
  [/\bevent driven\b/gi, "event-driven"],
  [/\bevent-driven architecture\b/gi, "event-driven architecture"],
  [/\bmessage queue\b/gi, "message queue"],
  [/\bmessage queues\b/gi, "message queues"],
  [/\bqueue worker\b/gi, "queue worker"],
  [/\bbackground job\b/gi, "background job"],
  [/\bbackground jobs\b/gi, "background jobs"],
  [/\bbull mq\b/gi, "BullMQ"],
  [/\bbullmq\b/gi, "BullMQ"],
  [/\brabbit mq\b/gi, "RabbitMQ"],
  [/\brabbitmq\b/gi, "RabbitMQ"],
  [/\bkafka\b/gi, "Kafka"],
  [/\bapache kafka\b/gi, "Apache Kafka"],
  [/\bpub sub\b/gi, "pub/sub"],
  [/\bpublish subscribe\b/gi, "publish-subscribe"],
  [/\bcaching\b/gi, "caching"],
  [/\bcache invalidation\b/gi, "cache invalidation"],
  [/\bdistributed system\b/gi, "distributed system"],
  [/\bdistributed systems\b/gi, "distributed systems"],
  [/\bscalability\b/gi, "scalability"],
  [/\bhorizontal scaling\b/gi, "horizontal scaling"],
  [/\bvertical scaling\b/gi, "vertical scaling"],
  [/\bfault tolerance\b/gi, "fault tolerance"],
  [/\bhigh availability\b/gi, "high availability"],
  [/\bsystem design\b/gi, "system design"],
  [/\bdesign pattern\b/gi, "design pattern"],
  [/\bdesign patterns\b/gi, "design patterns"],
  [/\bmvc\b/gi, "MVC"],
  [/\bm v c\b/gi, "MVC"],
  [/\brepository pattern\b/gi, "repository pattern"],
  [/\bfactory pattern\b/gi, "factory pattern"],
  [/\bsingleton pattern\b/gi, "singleton pattern"],
  [/\bdependency injection\b/gi, "dependency injection"],

  // =========================
  // AI / LLM / RAG
  // =========================
  [/\bopen ai\b/gi, "OpenAI"],
  [/\bopenai\b/gi, "OpenAI"],
  [/\bopen router\b/gi, "OpenRouter"],
  [/\bopenrouter\b/gi, "OpenRouter"],
  [/\bllm\b/gi, "LLM"],
  [/\bl l m\b/gi, "LLM"],
  [/\blarge language model\b/gi, "large language model"],
  [/\brag\b/gi, "RAG"],
  [/\br a g\b/gi, "RAG"],
  [/\bretrieval augmented generation\b/gi, "retrieval-augmented generation"],
  [/\bvector search\b/gi, "vector search"],
  [/\bsemantic search\b/gi, "semantic search"],
  [/\bchunking\b/gi, "chunking"],
  [/\breranking\b/gi, "reranking"],
  [/\bre ranking\b/gi, "reranking"],
  [/\bprompt engineering\b/gi, "prompt engineering"],
  [/\bprompt builder\b/gi, "prompt builder"],
  [/\bcontext window\b/gi, "context window"],
  [/\btoken limit\b/gi, "token limit"],
  [/\bhallucination\b/gi, "hallucination"],
  [/\bhallucinations\b/gi, "hallucinations"],
  [/\bspeech to text\b/gi, "speech-to-text"],
  [/\bstt\b/gi, "STT"],
  [/\bs t t\b/gi, "STT"],
  [/\bdeep gram\b/gi, "Deepgram"],
  [/\bdeepgram\b/gi, "Deepgram"],
  [/\btranscription\b/gi, "transcription"],
  [/\btranscript\b/gi, "transcript"],

  // =========================
  // Testing / quality
  // =========================
  [/\bunit test\b/gi, "unit test"],
  [/\bunit tests\b/gi, "unit tests"],
  [/\bintegration test\b/gi, "integration test"],
  [/\bintegration tests\b/gi, "integration tests"],
  [/\be two e\b/gi, "E2E"],
  [/\be2e\b/gi, "E2E"],
  [/\bend to end\b/gi, "end-to-end"],
  [/\bjest\b/gi, "Jest"],
  [/\bvitest\b/gi, "Vitest"],
  [/\bplay wright\b/gi, "Playwright"],
  [/\bplaywright\b/gi, "Playwright"],
  [/\bcypress\b/gi, "Cypress"],
  [/\bpost man\b/gi, "Postman"],
  [/\bpostman\b/gi, "Postman"],
  [/\bswagger\b/gi, "Swagger"],
  [/\bopen api\b/gi, "OpenAPI"],
  [/\bapi documentation\b/gi, "API documentation"],
  [/\bcode review\b/gi, "code review"],
  [/\bpull request\b/gi, "pull request"],
  [/\bmerge request\b/gi, "merge request"],
  [/\bbug fix\b/gi, "bug fix"],
  [/\bhot fix\b/gi, "hotfix"],
  [/\bregression\b/gi, "regression"],

  // =========================
  // Languages / tools
  // =========================
  [/\bpython\b/gi, "Python"],
  [/\bpy thon\b/gi, "Python"],
  [/\bjava\b/gi, "Java"],
  [/\bc sharp\b/gi, "C#"],
  [/\bc plus plus\b/gi, "C++"],
  [/\bc plus\b/gi, "C++"],
  [/\bgolang\b/gi, "Go"],
  [/\bgo lang\b/gi, "Go"],
  [/\brust\b/gi, "Rust"],
  [/\bphp\b/gi, "PHP"],
  [/\bp h p\b/gi, "PHP"],
  [/\bruby\b/gi, "Ruby"],
  [/\bkotlin\b/gi, "Kotlin"],
  [/\bswift\b/gi, "Swift"],
  [/\bbash script\b/gi, "Bash script"],
  [/\bshell script\b/gi, "shell script"],
  [/\bterminal\b/gi, "terminal"],
  [/\bcli\b/gi, "CLI"],
  [/\bc l i\b/gi, "CLI"],
  [/\bnpm\b/gi, "npm"],
  [/\bn p m\b/gi, "npm"],
  [/\byarn\b/gi, "Yarn"],
  [/\bpnpm\b/gi, "pnpm"],
  [/\bp n p m\b/gi, "pnpm"],
  [/\bpackage json\b/gi, "package.json"],
  [/\bts config\b/gi, "tsconfig"],
  [/\btsconfig\b/gi, "tsconfig"],
  [/\bes lint\b/gi, "ESLint"],
  [/\beslint\b/gi, "ESLint"],
  [/\bprettier\b/gi, "Prettier"],

  // =========================
  // Desktop / ScribeShade-specific stack
  // =========================
  [/\btauri\b/gi, "Tauri"],
  [/\btory\b/gi, "Tauri"],
  [/\brust layer\b/gi, "Rust layer"],
  [/\bweb view\b/gi, "WebView"],
  [/\bwebview two\b/gi, "WebView2"],
  [/\bwebview2\b/gi, "WebView2"],
  [/\bwk web view\b/gi, "WKWebView"],
  [/\bscreen capture kit\b/gi, "ScreenCaptureKit"],
  [/\bscreencapturekit\b/gi, "ScreenCaptureKit"],
  [/\bsystem audio\b/gi, "system audio"],
  [/\bloop back audio\b/gi, "loopback audio"],
  [/\bloopback audio\b/gi, "loopback audio"],
  [/\bmicrophone capture\b/gi, "microphone capture"],
  [/\bcpal\b/gi, "cpal"],
  [/\bc pal\b/gi, "cpal"],
  [/\bpcm\b/gi, "PCM"],
  [/\bp c m\b/gi, "PCM"],
  [/\bsse credit events\b/gi, "SSE credit events"],
  [/\bfloating overlay\b/gi, "floating overlay"],
  [/\bmini overlay\b/gi, "mini overlay"],
  [/\blauncher window\b/gi, "launcher window"],
  [/\bactive session\b/gi, "active session"],
  [/\bheartbeat\b/gi, "heartbeat"],

  // =========================
  // Interview / resume common phrases
  // =========================
  [/\btell me about your self\b/gi, "tell me about yourself"],
  [/\btell me about yourself\b/gi, "tell me about yourself"],
  [/\bwalk me through your resume\b/gi, "walk me through your resume"],
  [/\bwork experience\b/gi, "work experience"],
  [/\bprofessional experience\b/gi, "professional experience"],
  [/\bcompany experience\b/gi, "company experience"],
  [/\byears of experience\b/gi, "years of experience"],
  [/\byear of experience\b/gi, "year of experience"],
  [/\brelevant experience\b/gi, "relevant experience"],
  [/\bprevious company\b/gi, "previous company"],
  [/\bcurrent company\b/gi, "current company"],
  [/\bnotice period\b/gi, "notice period"],
  [/\bexpected salary\b/gi, "expected salary"],
  [/\bcurrent salary\b/gi, "current salary"],
  [/\bctc\b/gi, "CTC"],
  [/\bc t c\b/gi, "CTC"],
  [/\blpa\b/gi, "LPA"],
  [/\bl p a\b/gi, "LPA"],
  [/\bstrengths and weakness\b/gi, "strengths and weaknesses"],
  [/\bstrength and weakness\b/gi, "strengths and weaknesses"],
  [/\bwhy should we hire you\b/gi, "why should we hire you"],
  [/\bwhy this company\b/gi, "why this company"],
  [/\bwhy do you want to join\b/gi, "why do you want to join"],
  [/\bproject explanation\b/gi, "project explanation"],
  [/\bexplain your project\b/gi, "explain your project"],
  [/\bproject architecture\b/gi, "project architecture"],
  [/\byour role in project\b/gi, "your role in the project"],
  [/\byour responsibility\b/gi, "your responsibility"],
  [/\byour responsibilities\b/gi, "your responsibilities"],
  [/\bchallenge faced\b/gi, "challenge faced"],
  [/\bchallenges faced\b/gi, "challenges faced"],
  [/\bproduction issue\b/gi, "production issue"],
  [/\bteam size\b/gi, "team size"],
  [/\bagile methodology\b/gi, "Agile methodology"],
  [/\bscrum\b/gi, "Scrum"],
  [/\bsprint planning\b/gi, "sprint planning"],
  [/\bdaily stand up\b/gi, "daily standup"],
  [/\bdaily standup\b/gi, "daily standup"],
  [/\bjira\b/gi, "Jira"],
  [/\bconfluence\b/gi, "Confluence"],

  // =========================
  // Common STT filler cleanup
  // =========================
  [/\bumm\b/gi, "um"],
  [/\bu m\b/gi, "um"],
  [/\buhh\b/gi, "uh"],
  [/\baah\b/gi, "ah"],
  [/\bahh\b/gi, "ah"],
  [/\bokay so\b/gi, "okay, so"],
  [/\bok so\b/gi, "okay, so"],
  [/\byeah so\b/gi, "yeah, so"],
  [/\byes so\b/gi, "yes, so"],
  [/\bi mean\b/gi, "I mean"],
  [/\byou know\b/gi, "you know"],
  [/\bsort of\b/gi, "sort of"],
  [/\bkind of\b/gi, "kind of"],
  [/\bas per my knowledge\b/gi, "as per my knowledge"],
  [/\baccording to my experience\b/gi, "according to my experience"],

  // =========================
  // Common non-technical corrections
  // =========================
  [/\bcandi date\b/gi, "candidate"],
  [/\binter view\b/gi, "interview"],
  [/\binterviewer\b/gi, "interviewer"],
  [/\binter view er\b/gi, "interviewer"],
  [/\bresume\b/gi, "resume"],
  [/\bresume\b/gi, "resume"],
  [/\bcv\b/gi, "CV"],
  [/\bc v\b/gi, "CV"],
  [/\bjob description\b/gi, "job description"],
  [/\bj d\b/gi, "JD"],
  [/\bjd\b/gi, "JD"],
  [/\bdesignation\b/gi, "designation"],
  [/\brole\b/gi, "role"],
  [/\bresponsibility\b/gi, "responsibility"],
  [/\bresponsibilities\b/gi, "responsibilities"],
  [/\bachievement\b/gi, "achievement"],
  [/\bachievements\b/gi, "achievements"],
  [/\bcommunication skill\b/gi, "communication skill"],
  [/\bcommunication skills\b/gi, "communication skills"],
  [/\bproblem solving\b/gi, "problem-solving"],
  [/\blogical thinking\b/gi, "logical thinking"],
  [/\banalytical thinking\b/gi, "analytical thinking"],
  [/\bcollaboration\b/gi, "collaboration"],
  [/\bteam work\b/gi, "teamwork"],
  [/\bownership\b/gi, "ownership"],
  [/\bleadership\b/gi, "leadership"],
  [/\bdeadline\b/gi, "deadline"],
  [/\bdeliverable\b/gi, "deliverable"],
  [/\bdeliverables\b/gi, "deliverables"],

  // =========================
  // Product / business words
  // =========================
  [/\bsaas\b/gi, "SaaS"],
  [/\bs a a s\b/gi, "SaaS"],
  [/\bcrm\b/gi, "CRM"],
  [/\bc r m\b/gi, "CRM"],
  [/\berp\b/gi, "ERP"],
  [/\be r p\b/gi, "ERP"],
  [/\badmin panel\b/gi, "admin panel"],
  [/\bdashboard\b/gi, "dashboard"],
  [/\buser management\b/gi, "user management"],
  [/\brole management\b/gi, "role management"],
  [/\bpayment gateway\b/gi, "payment gateway"],
  [/\brazor pay\b/gi, "Razorpay"],
  [/\brazorpay\b/gi, "Razorpay"],
  [/\bstripe\b/gi, "Stripe"],
  [/\bsubscription\b/gi, "subscription"],
  [/\bcredit system\b/gi, "credit system"],
  [/\binvoice\b/gi, "invoice"],
  [/\breporting module\b/gi, "reporting module"],
  [/\banalytics\b/gi, "analytics"],
  [/\buser onboarding\b/gi, "user onboarding"],

  // =========================
  // Common API/status terms
  // =========================
  [/\bstatus code\b/gi, "status code"],
  [/\bstatus codes\b/gi, "status codes"],
  [/\bfour zero four\b/gi, "404"],
  [/\bfive hundred\b/gi, "500"],
  [/\bfive zero zero\b/gi, "500"],
  [/\btwo hundred\b/gi, "200"],
  [/\btwo zero one\b/gi, "201"],
  [/\bfour zero one\b/gi, "401"],
  [/\bfour zero three\b/gi, "403"],
  [/\bbad request\b/gi, "bad request"],
  [/\bnot found\b/gi, "not found"],
  [/\binternal server error\b/gi, "internal server error"],
  [/\bpayload\b/gi, "payload"],
  [/\brequest body\b/gi, "request body"],
  [/\bresponse body\b/gi, "response body"],
  [/\bquery params\b/gi, "query params"],
  [/\bquery parameters\b/gi, "query parameters"],
  [/\bpath params\b/gi, "path params"],
  [/\bheaders\b/gi, "headers"],
  [/\bcors\b/gi, "CORS"],
  [/\bc o r s\b/gi, "CORS"],
  [/\bjson\b/gi, "JSON"],
  [/\bj son\b/gi, "JSON"],
  [/\bxml\b/gi, "XML"],

  // =========================
  // Mobile / other frameworks
  // =========================
  [/\breact native\b/gi, "React Native"],
  [/\bflutter\b/gi, "Flutter"],
  [/\bdart\b/gi, "Dart"],
  [/\bandroid\b/gi, "Android"],
  [/\bios\b/gi, "iOS"],
  [/\bi o s\b/gi, "iOS"],
  [/\bswift ui\b/gi, "SwiftUI"],

  // =========================
  // Data structures / algorithms
  // =========================
  [/\bdsa\b/gi, "DSA"],
  [/\bd s a\b/gi, "DSA"],
  [/\bdata structure\b/gi, "data structure"],
  [/\bdata structures\b/gi, "data structures"],
  [/\balgorithm\b/gi, "algorithm"],
  [/\balgorithms\b/gi, "algorithms"],
  [/\barray\b/gi, "array"],
  [/\barrays\b/gi, "arrays"],
  [/\blinked list\b/gi, "linked list"],
  [/\bstack\b/gi, "stack"],
  [/\bqueue\b/gi, "queue"],
  [/\bhash map\b/gi, "hash map"],
  [/\bhash table\b/gi, "hash table"],
  [/\bbinary tree\b/gi, "binary tree"],
  [/\bbinary search tree\b/gi, "binary search tree"],
  [/\bgraph traversal\b/gi, "graph traversal"],
  [/\bbfs\b/gi, "BFS"],
  [/\bb f s\b/gi, "BFS"],
  [/\bdfs\b/gi, "DFS"],
  [/\bd f s\b/gi, "DFS"],
  [/\btime complexity\b/gi, "time complexity"],
  [/\bspace complexity\b/gi, "space complexity"],
  [/\bbig o\b/gi, "Big O"],
  [/\bo of n\b/gi, "O(n)"],
  [/\bo one\b/gi, "O(1)"],
  [/\bo log n\b/gi, "O(log n)"],

  // =========================
  // Common words that affect intent
  // =========================
  [/\bexplain that\b/gi, "explain that"],
  [/\bexplain it\b/gi, "explain it"],
  [/\bhow it works\b/gi, "how it works"],
  [/\bhow this works\b/gi, "how this works"],
  [/\bhow did you implement\b/gi, "how did you implement"],
  [/\bwhat was your role\b/gi, "what was your role"],
  [/\bwhat did you do\b/gi, "what did you do"],
  [/\bwhy did you use\b/gi, "why did you use"],
  [/\bwhat is the difference between\b/gi, "what is the difference between"],
  [/\bdifference between\b/gi, "difference between"],
  [/\bcompare between\b/gi, "compare"],
  [/\bpros and cons\b/gi, "pros and cons"],
  [/\badvantages and disadvantages\b/gi, "advantages and disadvantages"],
];

export function normalizeSttTranscript(text: string): string {
  if (!text?.trim()) return text || "";
  let next = text;
  for (const [pattern, replacement] of STT_CORRECTIONS) {
    next = next.replace(pattern, replacement);
  }
  return next.replace(/\s+/g, " ").trim();
}
